# coding: utf-8

"""
    SpecPipe Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import specpipe
from specpipe.models.update_device_request import UpdateDeviceRequest  # noqa: E501
from specpipe.rest import ApiException


class TestUpdateDeviceRequest(unittest.TestCase):
    """UpdateDeviceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateDeviceRequest(self):
        """Test UpdateDeviceRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = specpipe.models.update_device_request.UpdateDeviceRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
