# coding: utf-8

"""
    SpecPipe Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import specpipe
from specpipe.models.update_iq_device_request import UpdateIqDeviceRequest  # noqa: E501
from specpipe.rest import ApiException


class TestUpdateIqDeviceRequest(unittest.TestCase):
    """UpdateIqDeviceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateIqDeviceRequest(self):
        """Test UpdateIqDeviceRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = specpipe.models.update_iq_device_request.UpdateIqDeviceRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
